var restaurantes = [
    {
        "nome": "Miscelânea",
        "telefone": "964089230",
        "online": true,
        "whatsapp": false,
        "mediaPreco": 1,
        "email": "miscelaniadowntown@gmail.com",
        "descricao": "Comida caseira e diversificada",
    },
    {
        "nome": "Quentinha da Ana",
        "telefone": "24948445",
        "online": false,
        "whatsapp": false,
        "mediaPreco": 1,
        "email": undefined,
        "descricao": "Comida caseira",
    },
    {
        "nome": "MegaÁrabe",
        "telefone": "39822209",
        "online": false,
        "whatsapp": false,
        "mediaPreco": 2,
        "email": undefined,
        "descricao": "Comida árabe e brasileira",
    },
    {
        "nome": "BioCarioca",
        "telefone": "35980036",
        "online": false,
        "whatsapp": false,
        "mediaPreco": 4,
        "email": undefined,
        "descricao": "Comida vegetariana",
    },
];
